version: "3.9"
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'streamapp'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './db-prod:/var/lib/mysql'
      - './local:/var/lib/mysql-files'

# for WebUI
  adminer:
    depends_on:
      - db
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  backend:
      container_name: "backend"
      build: "app"
      ports:
        - "5000:5000"
      expose:
        - 5000
      
